package Quizgame.shared;

import java.io.Serializable;

public enum MessageType implements Serializable {
    ERROR,
    USERNAME_REQUEST,
    USERNAME,
    USERNAME_OK,
    USERNAME_TAKEN,
    GAME_START,
    QUESTION,
    ANSWER,
    RESULT_ROUND,
    START_NEXT_ROUND,
    GAME_FINISHED,
    MATCHMAKING,
    MATCHMAKING_WAITING_FOR_OPPONENT,
    WAITING,
    DUMMY,
    GIVE_UP,
    MOVE_TO_MENU,
    SETTINGS_AVATAR_CHANGED,
    CHOOSING_CATEGORIES,


    //for authentication
    LOGIN_REQUEST,
    LOGIN_OK,
    LOGIN_WRONG_PASSWORD,
    LOGIN_USER_NOT_FOUND,
    LOGIN_CREATE_REQUEST,
    LOGIN_CREATE_OK,
    LOGIN_CREATE_FAIL
}
